### PR TITLE
Fix: use correct sequence of parameters for wp_set_password()

### LINKED ISSUE #1: wp_set_password() parameter sequence is incorrect and causes a fatal error when disabling a user
https://github.com/humanmade/disable-accounts/blob/99a39618f56cc2c161d9544b52b764499af3602a/inc/namespace.php#L120

[wp_set_password](https://developer.wordpress.org/reference/functions/wp_set_password/) takes first parameter as password and second is user id. but in the above line first parameter is user_id and second is password.

### PR DESCRIPTION
**Pull request by Nikschavan**
Fixes #1

### CODE REVIEW

File: inc/namespace.php [hunk 1]
```diff
@@ -117,7 +117,7 @@ function disable_user( WP_User $user ) : void {
 	// Change the user's password to a random one. This will immediately halt
 	// access for that user.
 	$random_password = wp_generate_password( 40, true, true );
-	wp_set_password( $user->ID, $random_password );
+	wp_set_password( $random_password, $user->ID );
```
Comment (rmccue) [inline inc/namespace.php:120]: 🤦

**Review by rmccue — APPROVED** [review]
